### PR TITLE
Prototype JSON navigator

### PR DESCRIPTION
**Pull request by DamienCassou**
Demo for issue #29.

capture d ecran de 2017-04-19 07-39-29

### CODE REVIEW

**Comment by DamienCassou** [comment]
New version. Pay attention: this prototype only works when there is no duplication in the json document (a value never appears twice).

screenshot from 2017-04-19 09-33-19

**Comment by mnp** [comment]
Well this is neat, but I'm getting hitch on the example:

```elisp
(hierarchy-examples-json-display-tree (hierarchy-examples-json--read-example))

Debugger entered--Lisp error: (void-function nil)
  nil((tree-widget :args ((tree-widget :args ((tree-widget :args ((tree-widget :args nil :tag "3") (tree-widget :args nil :tag "2") (tree-widget :args nil :tag "1")) :tag "[1, 2, 3]")) :tag "array") (tree-widget :args ((tree-widget :args nil :tag ":json-null")) :tag "null") (tree-widget :args ((tree-widget :args nil :tag ":json-false")) :tag "false") (tree-widget :args ((tree-widget :args nil :tag "t")) :tag "true") (tree-widget :args ((tree-widget :args ((tree-widget :args (...) :tag "c") (tree-widget :args (...) :tag "a")) :tag "{\"a\": b, \"c\": d}")) :tag "object") (tree-widget :args ((tree-widget :args nil :tag "42")) :tag "number") (tree-widget :args ((tree-widget :args nil :tag "animal1")) :tag "string")) :tag "{\"string\": animal1, \"number\": 42, \"object\": {…}, …}"))
  widget-apply((tree-widget :args ((tree-widget :args ((tree-widget :args ((tree-widget :args nil :tag "3") (tree-widget :args nil :tag "2") (tree-widget :args nil :tag "1")) :tag "[1, 2, 3]")) :tag "array") (tree-widget :args ((tree-widget :args nil :tag ":json-null")) :tag "null") (tree-widget :args ((tree-widget :args nil :tag ":json-false")) :tag "false") (tree-widget :args ((tree-widget :args nil :tag "t")) :tag "true") (tree-widget :args ((tree-widget :args ((tree-widget :args (...) :tag "c") (tree-widget :args (...) :tag "a")) :tag "{\"a\": b, \"c\": d}")) :tag "object") (tree-widget :args ((tree-widget :args nil :tag "42")) :tag "number") (tree-widget :args ((tree-widget :args nil :tag "animal1")) :tag "string")) :tag "{\"string\": animal1, \"number\": 42, \"object\": {…}, …}") :create)
  widget-create((tree-widget :args ((tree-widget :args ((tree-widget :args ((tree-widget :args nil :tag "3") (tree-widget :args nil :tag "2") (tree-widget :args nil :tag "1")) :tag "[1, 2, 3]")) :tag "array") (tree-widget :args ((tree-widget :args nil :tag ":json-null")) :tag "null") (tree-widget :args ((tree-widget :args nil :tag ":json-false")) :tag "false") (tree-widget :args ((tree-widget :args nil :tag "t")) :tag "true") (tree-widget :args ((tree-widget :args ((tree-widget :args (...) :tag "c") (tree-widget :args (...) :tag "a")) :tag "{\"a\": b, \"c\": d}")) :tag "object") (tree-widget :args ((tree-widget :args nil :tag "42")) :tag "number") (tree-widget :args ((tree-widget :args nil :tag "animal1")) :tag "string")) :tag "{\"string\": animal1, \"number\": 42, \"object\": {…}, …}"))
  (let ((inhibit-read-only t)) (erase-buffer) (widget-create tree-widget) (goto-char (point-min)))
  (save-current-buffer (set-buffer (get-buffer-create "*hierarchy-examples-json-tree*")) (set (make-local-variable (quote buffer-read-only)) t) (let ((inhibit-read-only t)) (erase-buffer) (widget-create tree-widget) (goto-char (point-min))) (switch-to-buffer (current-buffer)))
  (let* ((hierarchy (hierarchy-examples-json-create-hierarchy json)) (tree-widget (hierarchy-convert-to-tree-widget hierarchy (function (lambda (item _) (hierarchy-examples-json--insert item)))))) (save-current-buffer (set-buffer (get-buffer-create "*hierarchy-examples-json-tree*")) (set (make-local-variable (quote buffer-read-only)) t) (let ((inhibit-read-only t)) (erase-buffer) (widget-create tree-widget) (goto-char (point-min))) (switch-to-buffer (current-buffer))))
  hierarchy-examples-json-display-tree(((string . "animal1") (number . 42) (object (a . "b") (c . "d")) (true . t) (false . :json-false) (null . :json-null) (array . [1 2 3])))
  eval((hierarchy-examples-json-display-tree (hierarchy-examples-json--read-example)) nil)
  elisp--eval-last-sexp(t)
  eval-last-sexp(t)
  eval-print-last-sexp(nil)
  funcall-interactively(eval-print-last-sexp nil)
  call-interactively(eval-print-last-sexp nil nil)
  command-execute(eval-print-last-sexp)
```

Emacs 25.1.1, tree-widget 22.1, wid-edit 21.1

**Comment by DamienCassou** [comment]
Can you reproduce with the filesystem example? Do you have more success with the tabulated view?

**Comment by mnp** [comment]
Got it.  The problem was both examples need to have...

```lisp
(require 'tree-widget)
```
The poor error from the interpreter didn't show what symbol was nil.

**Comment by DamienCassou** [comment]
Thank you very much, I fixed it for both example files.

Regarding the prototype, is this something like that you had in mind? Would you like something else?

**Comment by DamienCassou** [comment]
I updated the code so that there is no more limitation on non-duplicated elements. You should be able to navigate any JSON document now.

**Comment by mnp** [comment]
This is already useful, thanks!  I'm envisioning building a high level UI on top.

**Comment by DamienCassou** [comment]
Mitchell Perilstein <notifications@github.com> writes:
> This is already useful, thanks!  I'm envisioning building a high level UI on top.

I advise you to copy this file out of the hierarchy repository so you
can do whatever you want with it. While using the hierarchy API, please
create tickets each time you find something not clear or if something is
missing or buggy.

Best,

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Pull request merged**
